# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - logging/json_logger
  - agents/prompt_tuning
  - agents/generation
  - agents/refiner
  - agents/review
  - agents/reflection
  - agents/ranking
  - agents/evolution
  - agents/meta_review
  - agents/proximity
  - agents/literature
  - agents/literature_ranking
  - agents/supervisor

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal: "Can generative AI models reduce the time required to make scientific discoveries in biomedical research?"

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
    - name: literature
      cls: co_ai.agents.literature.LiteratureAgent
      enabled: true
      iterations: 1
    - name: literature_ranking
      cls: co_ai.agents.generic.GenericAgent
      enabled: true
      iterations: 1
    - name: generation
      cls: co_ai.agents.generation.GenerationAgent
      enabled: true
      iterations: 1
    # - name: reflection
    #   cls: co_ai.agents.reflection.ReflectionAgent
    #   enabled: true
    #   iterations: 1
    # - name: review
    #   cls: co_ai.agents.review.ReviewAgent
    #   enabled: true
    #   iterations: 1
    # - name: proximity
    #   cls: co_ai.agents.proximity.ProximityAgent
    #   enabled: true
    #   iterations: 1
    # - name: ranking
    #   cls: co_ai.agents.ranking.RankingAgent
    #   enabled: true
    #   iterations: 1
    # - name: evolution
    #   cls: co_ai.agents.evolution.EvolutionAgent
    #   enabled: true
    #   iterations: 1
    # - name: meta_review
    #   cls: co_ai.agents.meta_review.MetaReviewAgent
    #   enabled: true
    #   iterations: 1
    # - name: prompt_tuning
    #   cls: co_ai.agents.prompt_tuning.PromptTuningAgent
    #   enabled: false
    #   iterations: 1
