# configs/agents/proximity.yaml
defaults:
  - /prompt_refiner/disabled

generic:
  name: generic
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_key: hypotheses   # add nodes
  output_key: generic  # change
  prompt_mode: file
  prompt_file: query_and_summarize.txt
  extraction_regex: "search query:<([^>]+)>\n(.*)"
  strategy: query_and_summarize
