# config/agents/generation.yaml
defaults:
  - /prompt_refiner/default

generation:
  name: generation
  enabled: true
  save_context: true
  skip_if_completed: true
  strategy : default
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null

  save_prompt: true
  prompt_mode: file
  prompt_file: out_of_the_box.txt
  improve_file: improve.txt
  improve_count: 3
  output_key: hypotheses
  prompt_match_re: Hypothesis\s+\d+:\s+(.*?)(?=\nHypothesis\s+\d+:|\Z)
  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity